<org.pentaho.metadata.model.Domain>
  <properties>
    <entry>
      <string>description</string>
      <org.pentaho.metadata.model.concept.types.LocalizedString>
        <localeStringMap>
          <entry>
            <string>en_US</string>
            <string>data model for Spoon Ltd</string>
          </entry>
        </localeStringMap>
      </org.pentaho.metadata.model.concept.types.LocalizedString>
    </entry>
    <entry>
      <string>name</string>
      <org.pentaho.metadata.model.concept.types.LocalizedString>
        <localeStringMap>
          <entry>
            <string>en_US</string>
            <string>spoon_ltd</string>
          </entry>
        </localeStringMap>
      </org.pentaho.metadata.model.concept.types.LocalizedString>
    </entry>
    <entry>
      <string>DOMAIN_TARGET_DATABASE</string>
      <string>target_db</string>
    </entry>
  </properties>
  <physicalModels/>
  <logicalModels>
    <org.pentaho.metadata.model.LogicalModel>
      <properties>
        <entry>
          <string>description</string>
          <org.pentaho.metadata.model.concept.types.LocalizedString>
            <localeStringMap>
              <entry>
                <string>en_US</string>
                <string>Includes revenue figures ...</string>
              </entry>
            </localeStringMap>
          </org.pentaho.metadata.model.concept.types.LocalizedString>
        </entry>
        <entry>
          <string>name</string>
          <org.pentaho.metadata.model.concept.types.LocalizedString>
            <localeStringMap>
              <entry>
                <string>en_US</string>
                <string>revenue</string>
              </entry>
            </localeStringMap>
          </org.pentaho.metadata.model.concept.types.LocalizedString>
        </entry>
      </properties>
      <logicalTables>
        <org.pentaho.metadata.model.LogicalTable>
          <properties>
            <entry>
              <string>PHYSICAL_TABLE_NAME</string>
              <string>fact_revenue</string>
            </entry>
            <entry>
              <string>description</string>
              <org.pentaho.metadata.model.concept.types.LocalizedString>
                <localeStringMap>
                  <entry>
                    <string>en_US</string>
                    <string>Contains all revenue data</string>
                  </entry>
                </localeStringMap>
              </org.pentaho.metadata.model.concept.types.LocalizedString>
            </entry>
            <entry>
              <string>name</string>
              <org.pentaho.metadata.model.concept.types.LocalizedString>
                <localeStringMap>
                  <entry>
                    <string>en_US</string>
                    <string>fact_revenue</string>
                  </entry>
                </localeStringMap>
              </org.pentaho.metadata.model.concept.types.LocalizedString>
            </entry>
            <entry>
              <string>tabletype</string>
              <org.pentaho.metadata.model.concept.types.TableType>FACT</org.pentaho.metadata.model.concept.types.TableType>
            </entry>
          </properties>
          <id>b140bf06-0a9f-4a36-82f7-a7a7497bc5f7</id>
          <logicalColumns>
            <org.pentaho.metadata.model.LogicalColumn>
              <properties>
                <entry>
                  <string>SOURCE_DB</string>
                  <string></string>
                </entry>
                <entry>
                  <string>ATTRIBUTE_TYPE</string>
                  <string>TECHNICAL_KEY</string>
                </entry>
                <entry>
                  <string>description</string>
                  <org.pentaho.metadata.model.concept.types.LocalizedString>
                    <localeStringMap>
                      <entry>
                        <string>en_US</string>
                        <string>Technical key</string>
                      </entry>
                    </localeStringMap>
                  </org.pentaho.metadata.model.concept.types.LocalizedString>
                </entry>
                <entry>
                  <string>CONVERSION_REMARKS</string>
                  <string>Key to dimension &apos;dim_date&apos;</string>
                </entry>
                <entry>
                  <string>name</string>
                  <org.pentaho.metadata.model.concept.types.LocalizedString>
                    <localeStringMap>
                      <entry>
                        <string>en_US</string>
                        <string>dim_date TK</string>
                      </entry>
                    </localeStringMap>
                  </org.pentaho.metadata.model.concept.types.LocalizedString>
                </entry>
                <entry>
                  <string>PRECISION</string>
                  <string></string>
                </entry>
                <entry>
                  <string>datatype</string>
                  <org.pentaho.metadata.model.concept.types.DataType>NUMERIC</org.pentaho.metadata.model.concept.types.DataType>
                </entry>
                <entry>
                  <string>SOURCE_COLUMN</string>
                  <string></string>
                </entry>
                <entry>
                  <string>SOURCE_TABLE</string>
                  <string></string>
                </entry>
                <entry>
                  <string>LENGTH</string>
                  <string>9</string>
                </entry>
                <entry>
                  <string>DIMENSION_NAME</string>
                  <string>dim_date</string>
                </entry>
                <entry>
                  <string>PHYSICAL_COLUMN_NAME</string>
                  <string>dim_date_tk</string>
                </entry>
              </properties>
              <id>fd1fa088-8ab0-4757-9862-349bd336f5f4</id>
              <logicalTable reference="../../.."/>
            </org.pentaho.metadata.model.LogicalColumn>
            <org.pentaho.metadata.model.LogicalColumn>
              <properties>
                <entry>
                  <string>SOURCE_DB</string>
                  <string></string>
                </entry>
                <entry>
                  <string>ATTRIBUTE_TYPE</string>
                  <string>TECHNICAL_KEY</string>
                </entry>
                <entry>
                  <string>description</string>
                  <org.pentaho.metadata.model.concept.types.LocalizedString>
                    <localeStringMap>
                      <entry>
                        <string>en_US</string>
                        <string>Technical/surrogate key</string>
                      </entry>
                    </localeStringMap>
                  </org.pentaho.metadata.model.concept.types.LocalizedString>
                </entry>
                <entry>
                  <string>CONVERSION_REMARKS</string>
                  <string>Key to dimension &apos;dim_country&apos;</string>
                </entry>
                <entry>
                  <string>name</string>
                  <org.pentaho.metadata.model.concept.types.LocalizedString>
                    <localeStringMap>
                      <entry>
                        <string>en_US</string>
                        <string>dim_country TK</string>
                      </entry>
                    </localeStringMap>
                  </org.pentaho.metadata.model.concept.types.LocalizedString>
                </entry>
                <entry>
                  <string>PRECISION</string>
                  <string></string>
                </entry>
                <entry>
                  <string>datatype</string>
                  <org.pentaho.metadata.model.concept.types.DataType>NUMERIC</org.pentaho.metadata.model.concept.types.DataType>
                </entry>
                <entry>
                  <string>SOURCE_COLUMN</string>
                  <string></string>
                </entry>
                <entry>
                  <string>SOURCE_TABLE</string>
                  <string></string>
                </entry>
                <entry>
                  <string>LENGTH</string>
                  <string>9</string>
                </entry>
                <entry>
                  <string>DIMENSION_NAME</string>
                  <string>dim_country</string>
                </entry>
                <entry>
                  <string>PHYSICAL_COLUMN_NAME</string>
                  <string>dim_country_tk</string>
                </entry>
              </properties>
              <id>7f194790-b2c0-4838-9cea-fe4384287c2a</id>
              <logicalTable reference="../../.."/>
            </org.pentaho.metadata.model.LogicalColumn>
            <org.pentaho.metadata.model.LogicalColumn>
              <properties>
                <entry>
                  <string>SOURCE_DB</string>
                  <string>source_db</string>
                </entry>
                <entry>
                  <string>ATTRIBUTE_TYPE</string>
                  <string>FACT</string>
                </entry>
                <entry>
                  <string>description</string>
                  <org.pentaho.metadata.model.concept.types.LocalizedString>
                    <localeStringMap>
                      <entry>
                        <string>en_US</string>
                        <string></string>
                      </entry>
                    </localeStringMap>
                  </org.pentaho.metadata.model.concept.types.LocalizedString>
                </entry>
                <entry>
                  <string>CONVERSION_REMARKS</string>
                  <string></string>
                </entry>
                <entry>
                  <string>name</string>
                  <org.pentaho.metadata.model.concept.types.LocalizedString>
                    <localeStringMap>
                      <entry>
                        <string>en_US</string>
                        <string>revenue</string>
                      </entry>
                    </localeStringMap>
                  </org.pentaho.metadata.model.concept.types.LocalizedString>
                </entry>
                <entry>
                  <string>PRECISION</string>
                  <string></string>
                </entry>
                <entry>
                  <string>datatype</string>
                  <org.pentaho.metadata.model.concept.types.DataType>NUMERIC</org.pentaho.metadata.model.concept.types.DataType>
                </entry>
                <entry>
                  <string>SOURCE_COLUMN</string>
                  <string>revenue</string>
                </entry>
                <entry>
                  <string>SOURCE_TABLE</string>
                  <string>revenue</string>
                </entry>
                <entry>
                  <string>LENGTH</string>
                  <string></string>
                </entry>
                <entry>
                  <string>DIMENSION_NAME</string>
                  <string></string>
                </entry>
                <entry>
                  <string>PHYSICAL_COLUMN_NAME</string>
                  <string>revenue</string>
                </entry>
              </properties>
              <id>1b2ad6c8-9bd8-453a-948c-5aa542e6f30b</id>
              <logicalTable reference="../../.."/>
            </org.pentaho.metadata.model.LogicalColumn>
          </logicalColumns>
        </org.pentaho.metadata.model.LogicalTable>
        <org.pentaho.metadata.model.LogicalTable>
          <properties>
            <entry>
              <string>PHYSICAL_TABLE_NAME</string>
              <string>dim_date</string>
            </entry>
            <entry>
              <string>description</string>
              <org.pentaho.metadata.model.concept.types.LocalizedString>
                <localeStringMap>
                  <entry>
                    <string>en_US</string>
                    <string>Date dimensions</string>
                  </entry>
                </localeStringMap>
              </org.pentaho.metadata.model.concept.types.LocalizedString>
            </entry>
            <entry>
              <string>name</string>
              <org.pentaho.metadata.model.concept.types.LocalizedString>
                <localeStringMap>
                  <entry>
                    <string>en_US</string>
                    <string>dim_date</string>
                  </entry>
                </localeStringMap>
              </org.pentaho.metadata.model.concept.types.LocalizedString>
            </entry>
            <entry>
              <string>tabletype</string>
              <org.pentaho.metadata.model.concept.types.TableType>DIMENSION</org.pentaho.metadata.model.concept.types.TableType>
            </entry>
            <entry>
              <string>DIMENSION_TYPE</string>
              <string>DATE</string>
            </entry>
          </properties>
          <id>d2f53ab7-b6c1-4d7a-b141-1e54960d3d5e</id>
          <logicalModel reference="../../.."/>
          <logicalColumns>
            <org.pentaho.metadata.model.LogicalColumn>
              <properties>
                <entry>
                  <string>SOURCE_DB</string>
                  <string></string>
                </entry>
                <entry>
                  <string>ATTRIBUTE_TYPE</string>
                  <string>TECHNICAL_KEY</string>
                </entry>
                <entry>
                  <string>description</string>
                  <org.pentaho.metadata.model.concept.types.LocalizedString>
                    <localeStringMap>
                      <entry>
                        <string>en_US</string>
                        <string>Technical key</string>
                      </entry>
                    </localeStringMap>
                  </org.pentaho.metadata.model.concept.types.LocalizedString>
                </entry>
                <entry>
                  <string>CONVERSION_REMARKS</string>
                  <string>Smart key yyyyMMdd</string>
                </entry>
                <entry>
                  <string>name</string>
                  <org.pentaho.metadata.model.concept.types.LocalizedString>
                    <localeStringMap>
                      <entry>
                        <string>en_US</string>
                        <string>Date TK</string>
                      </entry>
                    </localeStringMap>
                  </org.pentaho.metadata.model.concept.types.LocalizedString>
                </entry>
                <entry>
                  <string>PRECISION</string>
                  <string>0</string>
                </entry>
                <entry>
                  <string>datatype</string>
                  <org.pentaho.metadata.model.concept.types.DataType>NUMERIC</org.pentaho.metadata.model.concept.types.DataType>
                </entry>
                <entry>
                  <string>SOURCE_COLUMN</string>
                  <string></string>
                </entry>
                <entry>
                  <string>SOURCE_TABLE</string>
                  <string></string>
                </entry>
                <entry>
                  <string>LENGTH</string>
                  <string>9</string>
                </entry>
                <entry>
                  <string>PHYSICAL_COLUMN_NAME</string>
                  <string>date_tk</string>
                </entry>
              </properties>
              <id>d1394201-6a9d-4e4b-83cf-ebccb08997ce</id>
              <logicalTable reference="../../.."/>
            </org.pentaho.metadata.model.LogicalColumn>
            <org.pentaho.metadata.model.LogicalColumn>
              <properties>
                <entry>
                  <string>SOURCE_DB</string>
                  <string></string>
                </entry>
                <entry>
                  <string>ATTRIBUTE_TYPE</string>
                  <string>ATTRIBUTE</string>
                </entry>
                <entry>
                  <string>description</string>
                  <org.pentaho.metadata.model.concept.types.LocalizedString>
                    <localeStringMap>
                      <entry>
                        <string>en_US</string>
                        <string>The date time value, ex. 2011/10/27 00:00:00, always at midnight</string>
                      </entry>
                    </localeStringMap>
                  </org.pentaho.metadata.model.concept.types.LocalizedString>
                </entry>
                <entry>
                  <string>CONVERSION_REMARKS</string>
                  <string></string>
                </entry>
                <entry>
                  <string>name</string>
                  <org.pentaho.metadata.model.concept.types.LocalizedString>
                    <localeStringMap>
                      <entry>
                        <string>en_US</string>
                        <string>Date field</string>
                      </entry>
                    </localeStringMap>
                  </org.pentaho.metadata.model.concept.types.LocalizedString>
                </entry>
                <entry>
                  <string>PRECISION</string>
                  <string></string>
                </entry>
                <entry>
                  <string>datatype</string>
                  <org.pentaho.metadata.model.concept.types.DataType>DATE</org.pentaho.metadata.model.concept.types.DataType>
                </entry>
                <entry>
                  <string>SOURCE_COLUMN</string>
                  <string></string>
                </entry>
                <entry>
                  <string>SOURCE_TABLE</string>
                  <string></string>
                </entry>
                <entry>
                  <string>LENGTH</string>
                  <string></string>
                </entry>
                <entry>
                  <string>PHYSICAL_COLUMN_NAME</string>
                  <string>date_field</string>
                </entry>
              </properties>
              <id>869bf0a0-8142-4598-9830-5137eda8a668</id>
              <logicalTable reference="../../.."/>
            </org.pentaho.metadata.model.LogicalColumn>
            <org.pentaho.metadata.model.LogicalColumn>
              <properties>
                <entry>
                  <string>SOURCE_DB</string>
                  <string></string>
                </entry>
                <entry>
                  <string>ATTRIBUTE_TYPE</string>
                  <string>ATTRIBUTE</string>
                </entry>
                <entry>
                  <string>description</string>
                  <org.pentaho.metadata.model.concept.types.LocalizedString>
                    <localeStringMap>
                      <entry>
                        <string>en_US</string>
                        <string>Year-Month-Day. ex. 2011/10/27</string>
                      </entry>
                    </localeStringMap>
                  </org.pentaho.metadata.model.concept.types.LocalizedString>
                </entry>
                <entry>
                  <string>CONVERSION_REMARKS</string>
                  <string>mask yyyy/MM/dd</string>
                </entry>
                <entry>
                  <string>name</string>
                  <org.pentaho.metadata.model.concept.types.LocalizedString>
                    <localeStringMap>
                      <entry>
                        <string>en_US</string>
                        <string>YMD</string>
                      </entry>
                    </localeStringMap>
                  </org.pentaho.metadata.model.concept.types.LocalizedString>
                </entry>
                <entry>
                  <string>PRECISION</string>
                  <string>0</string>
                </entry>
                <entry>
                  <string>datatype</string>
                  <org.pentaho.metadata.model.concept.types.DataType>STRING</org.pentaho.metadata.model.concept.types.DataType>
                </entry>
                <entry>
                  <string>SOURCE_COLUMN</string>
                  <string></string>
                </entry>
                <entry>
                  <string>SOURCE_TABLE</string>
                  <string></string>
                </entry>
                <entry>
                  <string>LENGTH</string>
                  <string>10</string>
                </entry>
                <entry>
                  <string>PHYSICAL_COLUMN_NAME</string>
                  <string>ymd</string>
                </entry>
              </properties>
              <id>ebd10960-45e6-442b-8d4e-5944de395cc4</id>
              <logicalTable reference="../../.."/>
            </org.pentaho.metadata.model.LogicalColumn>
            <org.pentaho.metadata.model.LogicalColumn>
              <properties>
                <entry>
                  <string>SOURCE_DB</string>
                  <string></string>
                </entry>
                <entry>
                  <string>ATTRIBUTE_TYPE</string>
                  <string>ATTRIBUTE</string>
                </entry>
                <entry>
                  <string>description</string>
                  <org.pentaho.metadata.model.concept.types.LocalizedString>
                    <localeStringMap>
                      <entry>
                        <string>en_US</string>
                        <string>Year-Month. ex. 2011/10</string>
                      </entry>
                    </localeStringMap>
                  </org.pentaho.metadata.model.concept.types.LocalizedString>
                </entry>
                <entry>
                  <string>CONVERSION_REMARKS</string>
                  <string>mask yyyy/MM</string>
                </entry>
                <entry>
                  <string>name</string>
                  <org.pentaho.metadata.model.concept.types.LocalizedString>
                    <localeStringMap>
                      <entry>
                        <string>en_US</string>
                        <string>YM</string>
                      </entry>
                    </localeStringMap>
                  </org.pentaho.metadata.model.concept.types.LocalizedString>
                </entry>
                <entry>
                  <string>PRECISION</string>
                  <string>0</string>
                </entry>
                <entry>
                  <string>datatype</string>
                  <org.pentaho.metadata.model.concept.types.DataType>STRING</org.pentaho.metadata.model.concept.types.DataType>
                </entry>
                <entry>
                  <string>SOURCE_COLUMN</string>
                  <string></string>
                </entry>
                <entry>
                  <string>SOURCE_TABLE</string>
                  <string></string>
                </entry>
                <entry>
                  <string>LENGTH</string>
                  <string>7</string>
                </entry>
                <entry>
                  <string>PHYSICAL_COLUMN_NAME</string>
                  <string>ym</string>
                </entry>
              </properties>
              <id>f623caab-ea57-4afb-9ed8-8947ad38587e</id>
              <logicalTable reference="../../.."/>
            </org.pentaho.metadata.model.LogicalColumn>
            <org.pentaho.metadata.model.LogicalColumn>
              <properties>
                <entry>
                  <string>SOURCE_DB</string>
                  <string></string>
                </entry>
                <entry>
                  <string>ATTRIBUTE_TYPE</string>
                  <string>ATTRIBUTE</string>
                </entry>
                <entry>
                  <string>description</string>
                  <org.pentaho.metadata.model.concept.types.LocalizedString>
                    <localeStringMap>
                      <entry>
                        <string>en_US</string>
                        <string>Quarter of a year. ex. 4</string>
                      </entry>
                    </localeStringMap>
                  </org.pentaho.metadata.model.concept.types.LocalizedString>
                </entry>
                <entry>
                  <string>CONVERSION_REMARKS</string>
                  <string>Map month to quarter: {1,2,3}=1, {4,5,6}=2, {7,8,9}=3, {10,11,12}=4</string>
                </entry>
                <entry>
                  <string>name</string>
                  <org.pentaho.metadata.model.concept.types.LocalizedString>
                    <localeStringMap>
                      <entry>
                        <string>en_US</string>
                        <string>Quarter</string>
                      </entry>
                    </localeStringMap>
                  </org.pentaho.metadata.model.concept.types.LocalizedString>
                </entry>
                <entry>
                  <string>PRECISION</string>
                  <string>0</string>
                </entry>
                <entry>
                  <string>datatype</string>
                  <org.pentaho.metadata.model.concept.types.DataType>NUMERIC</org.pentaho.metadata.model.concept.types.DataType>
                </entry>
                <entry>
                  <string>SOURCE_COLUMN</string>
                  <string></string>
                </entry>
                <entry>
                  <string>SOURCE_TABLE</string>
                  <string></string>
                </entry>
                <entry>
                  <string>LENGTH</string>
                  <string>1</string>
                </entry>
                <entry>
                  <string>PHYSICAL_COLUMN_NAME</string>
                  <string>quarter</string>
                </entry>
              </properties>
              <id>f96dc598-b397-4e3c-85a9-f90b96ea956b</id>
              <logicalTable reference="../../.."/>
            </org.pentaho.metadata.model.LogicalColumn>
            <org.pentaho.metadata.model.LogicalColumn>
              <properties>
                <entry>
                  <string>SOURCE_DB</string>
                  <string></string>
                </entry>
                <entry>
                  <string>ATTRIBUTE_TYPE</string>
                  <string>ATTRIBUTE</string>
                </entry>
                <entry>
                  <string>description</string>
                  <org.pentaho.metadata.model.concept.types.LocalizedString>
                    <localeStringMap>
                      <entry>
                        <string>en_US</string>
                        <string>Quarter of a year code. ex. Q4</string>
                      </entry>
                    </localeStringMap>
                  </org.pentaho.metadata.model.concept.types.LocalizedString>
                </entry>
                <entry>
                  <string>CONVERSION_REMARKS</string>
                  <string>prepend quarter with &apos;Q&apos;</string>
                </entry>
                <entry>
                  <string>name</string>
                  <org.pentaho.metadata.model.concept.types.LocalizedString>
                    <localeStringMap>
                      <entry>
                        <string>en_US</string>
                        <string>Quarter code</string>
                      </entry>
                    </localeStringMap>
                  </org.pentaho.metadata.model.concept.types.LocalizedString>
                </entry>
                <entry>
                  <string>PRECISION</string>
                  <string>0</string>
                </entry>
                <entry>
                  <string>datatype</string>
                  <org.pentaho.metadata.model.concept.types.DataType>STRING</org.pentaho.metadata.model.concept.types.DataType>
                </entry>
                <entry>
                  <string>SOURCE_COLUMN</string>
                  <string></string>
                </entry>
                <entry>
                  <string>SOURCE_TABLE</string>
                  <string></string>
                </entry>
                <entry>
                  <string>LENGTH</string>
                  <string>2</string>
                </entry>
                <entry>
                  <string>PHYSICAL_COLUMN_NAME</string>
                  <string>quarter_code</string>
                </entry>
              </properties>
              <id>358a33e3-bc8f-4d4a-bac0-f794ccee6d65</id>
              <logicalTable reference="../../.."/>
            </org.pentaho.metadata.model.LogicalColumn>
            <org.pentaho.metadata.model.LogicalColumn>
              <properties>
                <entry>
                  <string>SOURCE_DB</string>
                  <string></string>
                </entry>
                <entry>
                  <string>ATTRIBUTE_TYPE</string>
                  <string>ATTRIBUTE</string>
                </entry>
                <entry>
                  <string>description</string>
                  <org.pentaho.metadata.model.concept.types.LocalizedString>
                    <localeStringMap>
                      <entry>
                        <string>en_US</string>
                        <string>Month of a year. ex. 12</string>
                      </entry>
                    </localeStringMap>
                  </org.pentaho.metadata.model.concept.types.LocalizedString>
                </entry>
                <entry>
                  <string>CONVERSION_REMARKS</string>
                  <string></string>
                </entry>
                <entry>
                  <string>name</string>
                  <org.pentaho.metadata.model.concept.types.LocalizedString>
                    <localeStringMap>
                      <entry>
                        <string>en_US</string>
                        <string>Month</string>
                      </entry>
                    </localeStringMap>
                  </org.pentaho.metadata.model.concept.types.LocalizedString>
                </entry>
                <entry>
                  <string>PRECISION</string>
                  <string>0</string>
                </entry>
                <entry>
                  <string>datatype</string>
                  <org.pentaho.metadata.model.concept.types.DataType>NUMERIC</org.pentaho.metadata.model.concept.types.DataType>
                </entry>
                <entry>
                  <string>SOURCE_COLUMN</string>
                  <string></string>
                </entry>
                <entry>
                  <string>SOURCE_TABLE</string>
                  <string></string>
                </entry>
                <entry>
                  <string>LENGTH</string>
                  <string>2</string>
                </entry>
                <entry>
                  <string>PHYSICAL_COLUMN_NAME</string>
                  <string>month</string>
                </entry>
              </properties>
              <id>a709d8f9-ab24-4fa1-81b3-dc87d9c857f7</id>
              <logicalTable reference="../../.."/>
            </org.pentaho.metadata.model.LogicalColumn>
            <org.pentaho.metadata.model.LogicalColumn>
              <properties>
                <entry>
                  <string>SOURCE_DB</string>
                  <string></string>
                </entry>
                <entry>
                  <string>ATTRIBUTE_TYPE</string>
                  <string>ATTRIBUTE</string>
                </entry>
                <entry>
                  <string>description</string>
                  <org.pentaho.metadata.model.concept.types.LocalizedString>
                    <localeStringMap>
                      <entry>
                        <string>en_US</string>
                        <string>Month of year, description. ex. January</string>
                      </entry>
                    </localeStringMap>
                  </org.pentaho.metadata.model.concept.types.LocalizedString>
                </entry>
                <entry>
                  <string>CONVERSION_REMARKS</string>
                  <string></string>
                </entry>
                <entry>
                  <string>name</string>
                  <org.pentaho.metadata.model.concept.types.LocalizedString>
                    <localeStringMap>
                      <entry>
                        <string>en_US</string>
                        <string>Month description</string>
                      </entry>
                    </localeStringMap>
                  </org.pentaho.metadata.model.concept.types.LocalizedString>
                </entry>
                <entry>
                  <string>PRECISION</string>
                  <string>0</string>
                </entry>
                <entry>
                  <string>datatype</string>
                  <org.pentaho.metadata.model.concept.types.DataType>STRING</org.pentaho.metadata.model.concept.types.DataType>
                </entry>
                <entry>
                  <string>SOURCE_COLUMN</string>
                  <string></string>
                </entry>
                <entry>
                  <string>SOURCE_TABLE</string>
                  <string></string>
                </entry>
                <entry>
                  <string>LENGTH</string>
                  <string>20</string>
                </entry>
                <entry>
                  <string>PHYSICAL_COLUMN_NAME</string>
                  <string>month_desc</string>
                </entry>
              </properties>
              <id>eec3b93e-da44-4ca4-95bb-375999ec515d</id>
              <logicalTable reference="../../.."/>
            </org.pentaho.metadata.model.LogicalColumn>
            <org.pentaho.metadata.model.LogicalColumn>
              <properties>
                <entry>
                  <string>SOURCE_DB</string>
                  <string></string>
                </entry>
                <entry>
                  <string>ATTRIBUTE_TYPE</string>
                  <string>ATTRIBUTE</string>
                </entry>
                <entry>
                  <string>description</string>
                  <org.pentaho.metadata.model.concept.types.LocalizedString>
                    <localeStringMap>
                      <entry>
                        <string>en_US</string>
                        <string>Month of year, short description. ex. JAN</string>
                      </entry>
                    </localeStringMap>
                  </org.pentaho.metadata.model.concept.types.LocalizedString>
                </entry>
                <entry>
                  <string>CONVERSION_REMARKS</string>
                  <string></string>
                </entry>
                <entry>
                  <string>name</string>
                  <org.pentaho.metadata.model.concept.types.LocalizedString>
                    <localeStringMap>
                      <entry>
                        <string>en_US</string>
                        <string>Month short</string>
                      </entry>
                    </localeStringMap>
                  </org.pentaho.metadata.model.concept.types.LocalizedString>
                </entry>
                <entry>
                  <string>PRECISION</string>
                  <string>0</string>
                </entry>
                <entry>
                  <string>datatype</string>
                  <org.pentaho.metadata.model.concept.types.DataType>STRING</org.pentaho.metadata.model.concept.types.DataType>
                </entry>
                <entry>
                  <string>SOURCE_COLUMN</string>
                  <string></string>
                </entry>
                <entry>
                  <string>SOURCE_TABLE</string>
                  <string></string>
                </entry>
                <entry>
                  <string>LENGTH</string>
                  <string>3</string>
                </entry>
                <entry>
                  <string>PHYSICAL_COLUMN_NAME</string>
                  <string>month_code</string>
                </entry>
              </properties>
              <id>a5bc4406-190d-4c39-925e-2724429d8c5b</id>
              <logicalTable reference="../../.."/>
            </org.pentaho.metadata.model.LogicalColumn>
            <org.pentaho.metadata.model.LogicalColumn>
              <properties>
                <entry>
                  <string>SOURCE_DB</string>
                  <string></string>
                </entry>
                <entry>
                  <string>ATTRIBUTE_TYPE</string>
                  <string>ATTRIBUTE</string>
                </entry>
                <entry>
                  <string>description</string>
                  <org.pentaho.metadata.model.concept.types.LocalizedString>
                    <localeStringMap>
                      <entry>
                        <string>en_US</string>
                        <string>Day of a month. ex. 31</string>
                      </entry>
                    </localeStringMap>
                  </org.pentaho.metadata.model.concept.types.LocalizedString>
                </entry>
                <entry>
                  <string>CONVERSION_REMARKS</string>
                  <string></string>
                </entry>
                <entry>
                  <string>name</string>
                  <org.pentaho.metadata.model.concept.types.LocalizedString>
                    <localeStringMap>
                      <entry>
                        <string>en_US</string>
                        <string>Day</string>
                      </entry>
                    </localeStringMap>
                  </org.pentaho.metadata.model.concept.types.LocalizedString>
                </entry>
                <entry>
                  <string>PRECISION</string>
                  <string>0</string>
                </entry>
                <entry>
                  <string>datatype</string>
                  <org.pentaho.metadata.model.concept.types.DataType>NUMERIC</org.pentaho.metadata.model.concept.types.DataType>
                </entry>
                <entry>
                  <string>SOURCE_COLUMN</string>
                  <string></string>
                </entry>
                <entry>
                  <string>SOURCE_TABLE</string>
                  <string></string>
                </entry>
                <entry>
                  <string>LENGTH</string>
                  <string>2</string>
                </entry>
                <entry>
                  <string>PHYSICAL_COLUMN_NAME</string>
                  <string>day</string>
                </entry>
              </properties>
              <id>f38d880d-e8d0-4330-98a7-d4bf0b78c918</id>
              <logicalTable reference="../../.."/>
            </org.pentaho.metadata.model.LogicalColumn>
            <org.pentaho.metadata.model.LogicalColumn>
              <properties>
                <entry>
                  <string>SOURCE_DB</string>
                  <string></string>
                </entry>
                <entry>
                  <string>ATTRIBUTE_TYPE</string>
                  <string>ATTRIBUTE</string>
                </entry>
                <entry>
                  <string>description</string>
                  <org.pentaho.metadata.model.concept.types.LocalizedString>
                    <localeStringMap>
                      <entry>
                        <string>en_US</string>
                        <string>Day of a year. ex. 364</string>
                      </entry>
                    </localeStringMap>
                  </org.pentaho.metadata.model.concept.types.LocalizedString>
                </entry>
                <entry>
                  <string>CONVERSION_REMARKS</string>
                  <string></string>
                </entry>
                <entry>
                  <string>name</string>
                  <org.pentaho.metadata.model.concept.types.LocalizedString>
                    <localeStringMap>
                      <entry>
                        <string>en_US</string>
                        <string>Day of year</string>
                      </entry>
                    </localeStringMap>
                  </org.pentaho.metadata.model.concept.types.LocalizedString>
                </entry>
                <entry>
                  <string>PRECISION</string>
                  <string>0</string>
                </entry>
                <entry>
                  <string>datatype</string>
                  <org.pentaho.metadata.model.concept.types.DataType>NUMERIC</org.pentaho.metadata.model.concept.types.DataType>
                </entry>
                <entry>
                  <string>SOURCE_COLUMN</string>
                  <string></string>
                </entry>
                <entry>
                  <string>SOURCE_TABLE</string>
                  <string></string>
                </entry>
                <entry>
                  <string>LENGTH</string>
                  <string>3</string>
                </entry>
                <entry>
                  <string>PHYSICAL_COLUMN_NAME</string>
                  <string>day_of_year</string>
                </entry>
              </properties>
              <id>06cc7ddf-beff-48b9-877b-f11f2aab489a</id>
              <logicalTable reference="../../.."/>
            </org.pentaho.metadata.model.LogicalColumn>
            <org.pentaho.metadata.model.LogicalColumn>
              <properties>
                <entry>
                  <string>SOURCE_DB</string>
                  <string></string>
                </entry>
                <entry>
                  <string>ATTRIBUTE_TYPE</string>
                  <string>ATTRIBUTE</string>
                </entry>
                <entry>
                  <string>description</string>
                  <org.pentaho.metadata.model.concept.types.LocalizedString>
                    <localeStringMap>
                      <entry>
                        <string>en_US</string>
                        <string>Day of a week. ex. Monday</string>
                      </entry>
                    </localeStringMap>
                  </org.pentaho.metadata.model.concept.types.LocalizedString>
                </entry>
                <entry>
                  <string>CONVERSION_REMARKS</string>
                  <string></string>
                </entry>
                <entry>
                  <string>name</string>
                  <org.pentaho.metadata.model.concept.types.LocalizedString>
                    <localeStringMap>
                      <entry>
                        <string>en_US</string>
                        <string>Day of week</string>
                      </entry>
                    </localeStringMap>
                  </org.pentaho.metadata.model.concept.types.LocalizedString>
                </entry>
                <entry>
                  <string>PRECISION</string>
                  <string>0</string>
                </entry>
                <entry>
                  <string>datatype</string>
                  <org.pentaho.metadata.model.concept.types.DataType>STRING</org.pentaho.metadata.model.concept.types.DataType>
                </entry>
                <entry>
                  <string>SOURCE_COLUMN</string>
                  <string></string>
                </entry>
                <entry>
                  <string>SOURCE_TABLE</string>
                  <string></string>
                </entry>
                <entry>
                  <string>LENGTH</string>
                  <string>15</string>
                </entry>
                <entry>
                  <string>PHYSICAL_COLUMN_NAME</string>
                  <string>day_of_week</string>
                </entry>
              </properties>
              <id>f6b89766-3bf0-40a4-8126-5b29ba92040e</id>
              <logicalTable reference="../../.."/>
            </org.pentaho.metadata.model.LogicalColumn>
            <org.pentaho.metadata.model.LogicalColumn>
              <properties>
                <entry>
                  <string>SOURCE_DB</string>
                  <string></string>
                </entry>
                <entry>
                  <string>ATTRIBUTE_TYPE</string>
                  <string>ATTRIBUTE</string>
                </entry>
                <entry>
                  <string>description</string>
                  <org.pentaho.metadata.model.concept.types.LocalizedString>
                    <localeStringMap>
                      <entry>
                        <string>en_US</string>
                        <string>Day of a week. ex. Monday</string>
                      </entry>
                    </localeStringMap>
                  </org.pentaho.metadata.model.concept.types.LocalizedString>
                </entry>
                <entry>
                  <string>CONVERSION_REMARKS</string>
                  <string></string>
                </entry>
                <entry>
                  <string>name</string>
                  <org.pentaho.metadata.model.concept.types.LocalizedString>
                    <localeStringMap>
                      <entry>
                        <string>en_US</string>
                        <string>Day of week description</string>
                      </entry>
                    </localeStringMap>
                  </org.pentaho.metadata.model.concept.types.LocalizedString>
                </entry>
                <entry>
                  <string>PRECISION</string>
                  <string>0</string>
                </entry>
                <entry>
                  <string>datatype</string>
                  <org.pentaho.metadata.model.concept.types.DataType>STRING</org.pentaho.metadata.model.concept.types.DataType>
                </entry>
                <entry>
                  <string>SOURCE_COLUMN</string>
                  <string></string>
                </entry>
                <entry>
                  <string>SOURCE_TABLE</string>
                  <string></string>
                </entry>
                <entry>
                  <string>LENGTH</string>
                  <string>20</string>
                </entry>
                <entry>
                  <string>PHYSICAL_COLUMN_NAME</string>
                  <string>day_of_week_desc</string>
                </entry>
              </properties>
              <id>f8e2ad01-6b81-4700-83c0-b98c4588051f</id>
              <logicalTable reference="../../.."/>
            </org.pentaho.metadata.model.LogicalColumn>
            <org.pentaho.metadata.model.LogicalColumn>
              <properties>
                <entry>
                  <string>SOURCE_DB</string>
                  <string></string>
                </entry>
                <entry>
                  <string>ATTRIBUTE_TYPE</string>
                  <string>ATTRIBUTE</string>
                </entry>
                <entry>
                  <string>description</string>
                  <org.pentaho.metadata.model.concept.types.LocalizedString>
                    <localeStringMap>
                      <entry>
                        <string>en_US</string>
                        <string>Day of a week, short description. ex. MON</string>
                      </entry>
                    </localeStringMap>
                  </org.pentaho.metadata.model.concept.types.LocalizedString>
                </entry>
                <entry>
                  <string>CONVERSION_REMARKS</string>
                  <string></string>
                </entry>
                <entry>
                  <string>name</string>
                  <org.pentaho.metadata.model.concept.types.LocalizedString>
                    <localeStringMap>
                      <entry>
                        <string>en_US</string>
                        <string>Day of week short</string>
                      </entry>
                    </localeStringMap>
                  </org.pentaho.metadata.model.concept.types.LocalizedString>
                </entry>
                <entry>
                  <string>PRECISION</string>
                  <string>0</string>
                </entry>
                <entry>
                  <string>datatype</string>
                  <org.pentaho.metadata.model.concept.types.DataType>STRING</org.pentaho.metadata.model.concept.types.DataType>
                </entry>
                <entry>
                  <string>SOURCE_COLUMN</string>
                  <string></string>
                </entry>
                <entry>
                  <string>SOURCE_TABLE</string>
                  <string></string>
                </entry>
                <entry>
                  <string>LENGTH</string>
                  <string>3</string>
                </entry>
                <entry>
                  <string>PHYSICAL_COLUMN_NAME</string>
                  <string>day_of_week_code</string>
                </entry>
              </properties>
              <id>e00ea6ca-8528-465b-a806-cc4f4d45ed2b</id>
              <logicalTable reference="../../.."/>
            </org.pentaho.metadata.model.LogicalColumn>
            <org.pentaho.metadata.model.LogicalColumn>
              <properties>
                <entry>
                  <string>SOURCE_DB</string>
                  <string></string>
                </entry>
                <entry>
                  <string>ATTRIBUTE_TYPE</string>
                  <string>ATTRIBUTE</string>
                </entry>
                <entry>
                  <string>description</string>
                  <org.pentaho.metadata.model.concept.types.LocalizedString>
                    <localeStringMap>
                      <entry>
                        <string>en_US</string>
                        <string>Week of a year. ex. 50</string>
                      </entry>
                    </localeStringMap>
                  </org.pentaho.metadata.model.concept.types.LocalizedString>
                </entry>
                <entry>
                  <string>CONVERSION_REMARKS</string>
                  <string></string>
                </entry>
                <entry>
                  <string>name</string>
                  <org.pentaho.metadata.model.concept.types.LocalizedString>
                    <localeStringMap>
                      <entry>
                        <string>en_US</string>
                        <string>Week of year</string>
                      </entry>
                    </localeStringMap>
                  </org.pentaho.metadata.model.concept.types.LocalizedString>
                </entry>
                <entry>
                  <string>PRECISION</string>
                  <string>0</string>
                </entry>
                <entry>
                  <string>datatype</string>
                  <org.pentaho.metadata.model.concept.types.DataType>NUMERIC</org.pentaho.metadata.model.concept.types.DataType>
                </entry>
                <entry>
                  <string>SOURCE_COLUMN</string>
                  <string></string>
                </entry>
                <entry>
                  <string>SOURCE_TABLE</string>
                  <string></string>
                </entry>
                <entry>
                  <string>LENGTH</string>
                  <string>2</string>
                </entry>
                <entry>
                  <string>PHYSICAL_COLUMN_NAME</string>
                  <string>week</string>
                </entry>
              </properties>
              <id>0a5af856-fa0c-4680-902c-6cf698e7cf83</id>
              <logicalTable reference="../../.."/>
            </org.pentaho.metadata.model.LogicalColumn>
          </logicalColumns>
        </org.pentaho.metadata.model.LogicalTable>
        <org.pentaho.metadata.model.LogicalTable>
          <properties>
            <entry>
              <string>PHYSICAL_TABLE_NAME</string>
              <string>dim_country</string>
            </entry>
            <entry>
              <string>description</string>
              <org.pentaho.metadata.model.concept.types.LocalizedString>
                <localeStringMap>
                  <entry>
                    <string>en_US</string>
                    <string>New table description</string>
                  </entry>
                </localeStringMap>
              </org.pentaho.metadata.model.concept.types.LocalizedString>
            </entry>
            <entry>
              <string>name</string>
              <org.pentaho.metadata.model.concept.types.LocalizedString>
                <localeStringMap>
                  <entry>
                    <string>en_US</string>
                    <string>dim_country</string>
                  </entry>
                </localeStringMap>
              </org.pentaho.metadata.model.concept.types.LocalizedString>
            </entry>
            <entry>
              <string>tabletype</string>
              <org.pentaho.metadata.model.concept.types.TableType>DIMENSION</org.pentaho.metadata.model.concept.types.TableType>
            </entry>
            <entry>
              <string>DIMENSION_TYPE</string>
              <string>SLOWLY_CHANGING_DIMENSION</string>
            </entry>
          </properties>
          <id>5758d7ca-c0d2-420e-832a-170fceef1c6a</id>
          <logicalModel reference="../../.."/>
          <logicalColumns>
            <org.pentaho.metadata.model.LogicalColumn>
              <properties>
                <entry>
                  <string>SOURCE_DB</string>
                  <string></string>
                </entry>
                <entry>
                  <string>ATTRIBUTE_TYPE</string>
                  <string>TECHNICAL_KEY</string>
                </entry>
                <entry>
                  <string>description</string>
                  <org.pentaho.metadata.model.concept.types.LocalizedString>
                    <localeStringMap>
                      <entry>
                        <string>en_US</string>
                        <string>Technical/surrogate key</string>
                      </entry>
                    </localeStringMap>
                  </org.pentaho.metadata.model.concept.types.LocalizedString>
                </entry>
                <entry>
                  <string>CONVERSION_REMARKS</string>
                  <string>Generated by PDI</string>
                </entry>
                <entry>
                  <string>name</string>
                  <org.pentaho.metadata.model.concept.types.LocalizedString>
                    <localeStringMap>
                      <entry>
                        <string>en_US</string>
                        <string>country_tk</string>
                      </entry>
                    </localeStringMap>
                  </org.pentaho.metadata.model.concept.types.LocalizedString>
                </entry>
                <entry>
                  <string>PRECISION</string>
                  <string>0</string>
                </entry>
                <entry>
                  <string>datatype</string>
                  <org.pentaho.metadata.model.concept.types.DataType>NUMERIC</org.pentaho.metadata.model.concept.types.DataType>
                </entry>
                <entry>
                  <string>SOURCE_COLUMN</string>
                  <string></string>
                </entry>
                <entry>
                  <string>SOURCE_TABLE</string>
                  <string></string>
                </entry>
                <entry>
                  <string>LENGTH</string>
                  <string>9</string>
                </entry>
                <entry>
                  <string>PHYSICAL_COLUMN_NAME</string>
                  <string>country_tk</string>
                </entry>
              </properties>
              <id>4143b007-36ea-4cad-aca9-b09894689325</id>
              <logicalTable reference="../../.."/>
            </org.pentaho.metadata.model.LogicalColumn>
            <org.pentaho.metadata.model.LogicalColumn>
              <properties>
                <entry>
                  <string>SOURCE_DB</string>
                  <string></string>
                </entry>
                <entry>
                  <string>ATTRIBUTE_TYPE</string>
                  <string>VERSION_FIELD</string>
                </entry>
                <entry>
                  <string>description</string>
                  <org.pentaho.metadata.model.concept.types.LocalizedString>
                    <localeStringMap>
                      <entry>
                        <string>en_US</string>
                        <string>The dimension version number (1, ...)</string>
                      </entry>
                    </localeStringMap>
                  </org.pentaho.metadata.model.concept.types.LocalizedString>
                </entry>
                <entry>
                  <string>CONVERSION_REMARKS</string>
                  <string>Generated by PDI</string>
                </entry>
                <entry>
                  <string>name</string>
                  <org.pentaho.metadata.model.concept.types.LocalizedString>
                    <localeStringMap>
                      <entry>
                        <string>en_US</string>
                        <string>Version</string>
                      </entry>
                    </localeStringMap>
                  </org.pentaho.metadata.model.concept.types.LocalizedString>
                </entry>
                <entry>
                  <string>PRECISION</string>
                  <string>0</string>
                </entry>
                <entry>
                  <string>datatype</string>
                  <org.pentaho.metadata.model.concept.types.DataType>NUMERIC</org.pentaho.metadata.model.concept.types.DataType>
                </entry>
                <entry>
                  <string>SOURCE_COLUMN</string>
                  <string></string>
                </entry>
                <entry>
                  <string>SOURCE_TABLE</string>
                  <string></string>
                </entry>
                <entry>
                  <string>LENGTH</string>
                  <string>4</string>
                </entry>
                <entry>
                  <string>PHYSICAL_COLUMN_NAME</string>
                  <string>version</string>
                </entry>
              </properties>
              <id>5f36ad8e-5080-49f4-a74b-52bb8910122a</id>
              <logicalTable reference="../../.."/>
            </org.pentaho.metadata.model.LogicalColumn>
            <org.pentaho.metadata.model.LogicalColumn>
              <properties>
                <entry>
                  <string>SOURCE_DB</string>
                  <string></string>
                </entry>
                <entry>
                  <string>ATTRIBUTE_TYPE</string>
                  <string>DATE_START</string>
                </entry>
                <entry>
                  <string>description</string>
                  <org.pentaho.metadata.model.concept.types.LocalizedString>
                    <localeStringMap>
                      <entry>
                        <string>en_US</string>
                        <string>The start date of the dimension validity range</string>
                      </entry>
                    </localeStringMap>
                  </org.pentaho.metadata.model.concept.types.LocalizedString>
                </entry>
                <entry>
                  <string>CONVERSION_REMARKS</string>
                  <string>Generated by PDI</string>
                </entry>
                <entry>
                  <string>name</string>
                  <org.pentaho.metadata.model.concept.types.LocalizedString>
                    <localeStringMap>
                      <entry>
                        <string>en_US</string>
                        <string>Date From</string>
                      </entry>
                    </localeStringMap>
                  </org.pentaho.metadata.model.concept.types.LocalizedString>
                </entry>
                <entry>
                  <string>PRECISION</string>
                  <string></string>
                </entry>
                <entry>
                  <string>datatype</string>
                  <org.pentaho.metadata.model.concept.types.DataType>DATE</org.pentaho.metadata.model.concept.types.DataType>
                </entry>
                <entry>
                  <string>SOURCE_COLUMN</string>
                  <string></string>
                </entry>
                <entry>
                  <string>SOURCE_TABLE</string>
                  <string></string>
                </entry>
                <entry>
                  <string>LENGTH</string>
                  <string></string>
                </entry>
                <entry>
                  <string>PHYSICAL_COLUMN_NAME</string>
                  <string>date_from</string>
                </entry>
              </properties>
              <id>00bc4332-cd12-4176-8ef0-d7dec4aa632c</id>
              <logicalTable reference="../../.."/>
            </org.pentaho.metadata.model.LogicalColumn>
            <org.pentaho.metadata.model.LogicalColumn>
              <properties>
                <entry>
                  <string>SOURCE_DB</string>
                  <string></string>
                </entry>
                <entry>
                  <string>ATTRIBUTE_TYPE</string>
                  <string>DATE_END</string>
                </entry>
                <entry>
                  <string>description</string>
                  <org.pentaho.metadata.model.concept.types.LocalizedString>
                    <localeStringMap>
                      <entry>
                        <string>en_US</string>
                        <string>The start date of the dimension validity range</string>
                      </entry>
                    </localeStringMap>
                  </org.pentaho.metadata.model.concept.types.LocalizedString>
                </entry>
                <entry>
                  <string>CONVERSION_REMARKS</string>
                  <string>Generated by PDI</string>
                </entry>
                <entry>
                  <string>name</string>
                  <org.pentaho.metadata.model.concept.types.LocalizedString>
                    <localeStringMap>
                      <entry>
                        <string>en_US</string>
                        <string>Date To</string>
                      </entry>
                    </localeStringMap>
                  </org.pentaho.metadata.model.concept.types.LocalizedString>
                </entry>
                <entry>
                  <string>PRECISION</string>
                  <string></string>
                </entry>
                <entry>
                  <string>datatype</string>
                  <org.pentaho.metadata.model.concept.types.DataType>DATE</org.pentaho.metadata.model.concept.types.DataType>
                </entry>
                <entry>
                  <string>SOURCE_COLUMN</string>
                  <string></string>
                </entry>
                <entry>
                  <string>SOURCE_TABLE</string>
                  <string></string>
                </entry>
                <entry>
                  <string>LENGTH</string>
                  <string></string>
                </entry>
                <entry>
                  <string>PHYSICAL_COLUMN_NAME</string>
                  <string>date_to</string>
                </entry>
              </properties>
              <id>9a499d2b-1dc8-433f-9e37-525792158bad</id>
              <logicalTable reference="../../.."/>
            </org.pentaho.metadata.model.LogicalColumn>
            <org.pentaho.metadata.model.LogicalColumn>
              <properties>
                <entry>
                  <string>SOURCE_DB</string>
                  <string>source_db</string>
                </entry>
                <entry>
                  <string>ATTRIBUTE_TYPE</string>
                  <string>NATURAL_KEY</string>
                </entry>
                <entry>
                  <string>description</string>
                  <org.pentaho.metadata.model.concept.types.LocalizedString>
                    <localeStringMap>
                      <entry>
                        <string>en_US</string>
                        <string>Natural key of the dimension</string>
                      </entry>
                    </localeStringMap>
                  </org.pentaho.metadata.model.concept.types.LocalizedString>
                </entry>
                <entry>
                  <string>CONVERSION_REMARKS</string>
                  <string>Copy from source table</string>
                </entry>
                <entry>
                  <string>name</string>
                  <org.pentaho.metadata.model.concept.types.LocalizedString>
                    <localeStringMap>
                      <entry>
                        <string>en_US</string>
                        <string>country_iso_code</string>
                      </entry>
                    </localeStringMap>
                  </org.pentaho.metadata.model.concept.types.LocalizedString>
                </entry>
                <entry>
                  <string>PRECISION</string>
                  <string></string>
                </entry>
                <entry>
                  <string>datatype</string>
                  <org.pentaho.metadata.model.concept.types.DataType>STRING</org.pentaho.metadata.model.concept.types.DataType>
                </entry>
                <entry>
                  <string>SOURCE_COLUMN</string>
                  <string>country_iso_code</string>
                </entry>
                <entry>
                  <string>SOURCE_TABLE</string>
                  <string>Countries</string>
                </entry>
                <entry>
                  <string>LENGTH</string>
                  <string>9</string>
                </entry>
                <entry>
                  <string>PHYSICAL_COLUMN_NAME</string>
                  <string>country_iso_code</string>
                </entry>
              </properties>
              <id>151c37bd-ef3b-4333-bfab-b2962e10c808</id>
              <logicalTable reference="../../.."/>
            </org.pentaho.metadata.model.LogicalColumn>
            <org.pentaho.metadata.model.LogicalColumn>
              <properties>
                <entry>
                  <string>SOURCE_DB</string>
                  <string>source_db</string>
                </entry>
                <entry>
                  <string>ATTRIBUTE_TYPE</string>
                  <string>OTHER</string>
                </entry>
                <entry>
                  <string>description</string>
                  <org.pentaho.metadata.model.concept.types.LocalizedString>
                    <localeStringMap>
                      <entry>
                        <string>en_US</string>
                        <string></string>
                      </entry>
                    </localeStringMap>
                  </org.pentaho.metadata.model.concept.types.LocalizedString>
                </entry>
                <entry>
                  <string>CONVERSION_REMARKS</string>
                  <string></string>
                </entry>
                <entry>
                  <string>name</string>
                  <org.pentaho.metadata.model.concept.types.LocalizedString>
                    <localeStringMap>
                      <entry>
                        <string>en_US</string>
                        <string>country_name</string>
                      </entry>
                    </localeStringMap>
                  </org.pentaho.metadata.model.concept.types.LocalizedString>
                </entry>
                <entry>
                  <string>PRECISION</string>
                  <string></string>
                </entry>
                <entry>
                  <string>datatype</string>
                  <org.pentaho.metadata.model.concept.types.DataType>STRING</org.pentaho.metadata.model.concept.types.DataType>
                </entry>
                <entry>
                  <string>SOURCE_COLUMN</string>
                  <string>country_name</string>
                </entry>
                <entry>
                  <string>SOURCE_TABLE</string>
                  <string>Countries</string>
                </entry>
                <entry>
                  <string>LENGTH</string>
                  <string>100</string>
                </entry>
                <entry>
                  <string>PHYSICAL_COLUMN_NAME</string>
                  <string>country_name</string>
                </entry>
              </properties>
              <id>bed2d6ce-2a6e-4e85-9b70-964cf451bd24</id>
              <logicalTable reference="../../.."/>
            </org.pentaho.metadata.model.LogicalColumn>
          </logicalColumns>
        </org.pentaho.metadata.model.LogicalTable>
      </logicalTables>
      <logicalRelationships>
        <org.pentaho.metadata.model.LogicalRelationship>
          <properties>
            <entry>
              <string>complex</string>
              <boolean>false</boolean>
            </entry>
            <entry>
              <string>relationship_type</string>
              <org.pentaho.metadata.model.concept.types.RelationshipType>UNDEFINED</org.pentaho.metadata.model.concept.types.RelationshipType>
            </entry>
          </properties>
          <fromTable reference="../../../logicalTables/org.pentaho.metadata.model.LogicalTable"/>
          <toTable reference="../../../logicalTables/org.pentaho.metadata.model.LogicalTable[2]"/>
          <fromColumn reference="../../../logicalTables/org.pentaho.metadata.model.LogicalTable/logicalColumns/org.pentaho.metadata.model.LogicalColumn"/>
          <toColumn reference="../../../logicalTables/org.pentaho.metadata.model.LogicalTable[2]/logicalColumns/org.pentaho.metadata.model.LogicalColumn"/>
        </org.pentaho.metadata.model.LogicalRelationship>
        <org.pentaho.metadata.model.LogicalRelationship>
          <properties>
            <entry>
              <string>complex</string>
              <boolean>false</boolean>
            </entry>
            <entry>
              <string>relationship_type</string>
              <org.pentaho.metadata.model.concept.types.RelationshipType>UNDEFINED</org.pentaho.metadata.model.concept.types.RelationshipType>
            </entry>
          </properties>
          <fromTable reference="../../../logicalTables/org.pentaho.metadata.model.LogicalTable"/>
          <toTable reference="../../../logicalTables/org.pentaho.metadata.model.LogicalTable[3]"/>
          <fromColumn reference="../../../logicalTables/org.pentaho.metadata.model.LogicalTable/logicalColumns/org.pentaho.metadata.model.LogicalColumn[2]"/>
          <toColumn reference="../../../logicalTables/org.pentaho.metadata.model.LogicalTable[3]/logicalColumns/org.pentaho.metadata.model.LogicalColumn"/>
        </org.pentaho.metadata.model.LogicalRelationship>
      </logicalRelationships>
      <categories/>
    </org.pentaho.metadata.model.LogicalModel>
  </logicalModels>
  <concepts/>
</org.pentaho.metadata.model.Domain>